### ISSUE TITLE
Mise en correction

### ISSUE THREAD

**Issue by DamGLT** [PolytechLyon/2019-isi3-graph-bouhana_galochet#1]
Bonjour / Bonsoir,

Nous sommes prêt à subir les foudres de votre correction!

**Comment by Slashgear** [comment]
Cool 😈 

- 👍 Le rapport c'est très bien, c'est ce que j'attend de vous (pas besoin de faire plus ou moins)

- Vous avez fait du bon boulot à renommer des variable c'est cool.

Je pense qu'on peut pousser le truc un peu, exemple ici

https://github.com/PolytechLyon/2019-isi3-graph-bouhana_galochet/blob/207d66b9fa5bfe9bed53be80405065945eefd9ae/src/main/java/graph/Graph.java#L86

Les variables à une lettre je ne suis pas un grand fan

- la javadoc sur une fonction et pas sur l'autre c'est étrange. 

https://github.com/PolytechLyon/2019-isi3-graph-bouhana_galochet/blob/207d66b9fa5bfe9bed53be80405065945eefd9ae/src/main/java/graph/Graph.java#L115-L126

- Le pattern iterator est compris, c'est très bien mais ne remarquez vous pas que vos deux classes BFS et DFS se ressemblent énormément ? ===> DRY

**Comment by AlizeeBouhana** [comment]
Bonjour,

Nous avons remplacé les variables avec des noms plus explicites et la javadoc est complétée pour l'ensemble de nos méthodes.
Nous avons complété la classe mère de BFS et DFS pour qu'elles puissent hériter de la méthode hasNext().

**Comment by Slashgear** [comment]
Bonsoir,

C'est mieux, mais il reste à regrouper un peu les algo du DFS et BFS qui se ressemblent beaucoup trop pour ne pas être mutualisés

**Comment by DamGLT** [comment]
Bonjour,

Nous avons mutualisé les algorithmes comme suggéré.

**Comment by Slashgear** [comment]
Olà

ça, ça ne me plait pas beaucoup ! ⚠️ 

https://github.com/PolytechLyon/2019-isi3-graph-bouhana_galochet/blob/5f43b8ee6999d83bd229f3d05496164dceeba4e8/src/main/java/graph/IteratorSearch.java#L46-L50

Si je rajoute un autre algorithme de parcours, tu vas devoir rajouter un `if` et c'est pas top top top.

Pourrais-ton faire descendre la fonction qui te retourne la variable mal nommée `nReturn` dans vos sous implémentation ?

**Comment by DamGLT** [comment]
Nos excuses pour ce flottement >_<

Nous avons apporté des corrections qui j'espère vous plairont plus!

La gestion de la liste reste dans la classe mère, les classes filles se chargent de déterminer le prochain nœud à traiter et appellent la méthode de la classe mère qui peuple la liste.
